=== luicahleo/fastDiciembre/AppWeb/WebContent/p01/xsd/tablon_comp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="Tprecio">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="1000"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:complexType name="Tanuncio">
    <xs:sequence>
      <xs:element name="fecha" type="xs:date" />
      <xs:element name="asunto" type="xs:string" />
      <xs:element name="texto" type="xs:string" />
      <xs:element name="precio" type="Tprecio" />
      <xs:element name="contacto" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="codigo" type="xs:string"/>
    <xs:attribute name="vendido" type="xs:string"/>
  </xs:complexType>
  
  <xs:complexType name="Ttablon">
    <xs:sequence>
      <xs:element name="anuncio" type="Tanuncio" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:element name="tablon" type="Ttablon" />
  
</xs:schema>

=== luicahleo/fastDiciembre/AppWeb/WebContent/p01/xsd/tablon_comp.xml
<?xml version="1.0" encoding="UTF-8"?>
<tablon
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="tablon_comp.xsd">

  <anuncio codigo="A000" vendido="no">
    <fecha>2014-09-22</fecha>
    <asunto> Vendo bicicleta </asunto>
    <texto> 2 anios, cambios en buen estado</texto>
    <precio>500</precio>
    <contacto> 95 456 456 </contacto>
  </anuncio>

  <anuncio codigo="A001" vendido="no">
    <fecha>2011-09-22</fecha>
    <asunto> Vendo moto </asunto>
    <texto> buena, bonita, barata</texto>
    <precio> 1000</precio>
    <contacto> 666 123 123 </contacto>
  </anuncio>

  <anuncio codigo="A002" vendido="si">
    <fecha>2011-09-24</fecha>
    <asunto> Vendo bici</asunto>
    <texto> muy bonita, con candado</texto>
    <precio> 90 </precio>
    <contacto> a@ese.com </contacto>
  </anuncio>

</tablon>
